
export const translations = {
    pt: {
        appTitle: 'Mentor',
        academiaStara: 'Academia Stara',
        myCourses: 'Meus Cursos',
        simulator3D: 'Simulador 3D',
        achievements: 'Conquistas',
        technicalTools: 'Ferramentas Técnicas',
        quickConsult: 'Consulta Rápida',
        manualsPDF: 'Manuais PDF',
        recentHistory: 'Histórico Recente',
        nozzle: 'Bico Pulverizador',
        sensor: 'Sensor Hidráulico',
        armWeld: 'Solda Braço A',
        ago20min: 'Há 20 min',
        ago2hours: 'Há 2 horas',
        yesterday: 'Ontem',
        language: 'Idioma',
        trainingMode: 'Modo Treinamento',
        operationMode: 'Modo Operação',
        machineTitle: 'Imperador 4000',
        pumpModule: 'Módulo de Bomba',
        gearComponent: 'Engrenagem de Transmissão',
        transmission: 'Transmissão CVT',
        botName: 'Stara Assistente',
        botStatus: 'Online',
        inputPlaceholder: 'Pergunte alguma coisa...',
        roleJunior: 'Operador Júnior',
        roleSenior: 'Operador Sênior',
        videoTitle: 'Vídeo Aula Prática',
        watchTutorial: 'Assistir Tutorial',
        lessonProgress: 'Progresso do Treinamento',
        nextLesson: 'Próxima lição: Desmontagem e Limpeza',
        standardProc: 'Procedimento Padrão',
        mandatoryChange: 'Troca obrigatória a cada 500h de uso. Utilize chave 12mm.',
        visualStep: 'Passo a passo visual para evitar vazamentos na flange.',
        juniorTag: 'JÚNIOR',
        operationalTag: 'OPERACIONAL',
        viewManual: 'Ver Manual',
        continueCourse: 'Continuar Curso',
        
        // Achievements
        level: 'Nível',
        totalXp: 'XP Total',
        nextLevel: 'Próximo Nível',
        completedCourses: 'Cursos Completos',
        badgeFirstLogin: 'Primeiros Passos',
        badgeFirstLoginDesc: 'Acessou o simulador pela primeira vez.',
        badgePumpMaster: 'Mestre da Bomba',
        badgePumpMasterDesc: 'Completou o módulo de manutenção de bombas sem erros.',
        badgeSafety: 'Segurança em 1º Lugar',
        badgeSafetyDesc: 'Realizou todos os procedimentos de segurança antes da operação.',
        badgeMechanic: 'Mecânico Certificado',
        badgeMechanicDesc: 'Acumule 100 horas de simulação técnica.',
        locked: 'Bloqueado',
        unlocked: 'Desbloqueado',

        // Chat Scripts
        trainingGreeting: 'Olá Vivian. Vamos continuar o treinamento?',
        trainingUserSim: 'Sim, claro! Onde paramos?',
        trainingBotResponse: 'Ótimo! Aqui está o vídeo sobre o Módulo de Bomba que paramos na última aula.',
        operationGreeting: 'Olá Roberto. Qual é a sua dúvida?',
        operationUserSim: 'Qual o torque recomendado para os parafusos da flange?',
        operationBotResponse: 'O torque recomendado é de 120Nm. Certifique-se de usar uma chave dinamométrica calibrada.',

        // Double Click Interaction
        trainingClickIntro: 'Você selecionou: ',
        trainingClickPrompt: 'O que você gostaria de aprender sobre esta peça?',
        optHowItWorks: 'Como Funciona?',
        optCommonErrors: 'Erros Comuns',
        
        opClickIntro: 'Diagnóstico Rápido: ',
        opClickDetails: '🛠 Ferramenta: Chave 12mm | ⚠️ Torque: 45Nm | 🔄 Troca: Se houver vazamento.',

        // AI Glasses Mode
        aiGlassesMode: 'Modo Óculos AI',
        startRemoteAssist: 'Iniciar Assistência Remota',
        listening: 'Ouvindo...',
        processing: 'Processando...',
        systemCheck: 'Checagem de Sistema',
        connectionStable: 'Conexão Estável',
        endCall: 'Encerrar Chamada',
        glassesOverlayText: 'Analizando componente visual. Módulo de Bomba detectado. Temperatura normal.',
    },
    es: {
        appTitle: 'Mentor',
        academiaStara: 'Academia Stara',
        myCourses: 'Mis Cursos',
        simulator3D: 'Simulador 3D',
        achievements: 'Logros',
        technicalTools: 'Herramientas Técnicas',
        quickConsult: 'Consulta Rápida',
        manualsPDF: 'Manuales PDF',
        recentHistory: 'Historial Reciente',
        nozzle: 'Boquilla Pulverizadora',
        sensor: 'Sensor Hidráulico',
        armWeld: 'Soldadura Brazo A',
        ago20min: 'Hace 20 min',
        ago2hours: 'Hace 2 horas',
        yesterday: 'Ayer',
        language: 'Idioma',
        trainingMode: 'Modo Entrenamiento',
        operationMode: 'Modo Operación',
        machineTitle: 'Imperador 4000',
        pumpModule: 'Módulo de Bomba',
        gearComponent: 'Engranaje de Transmisión',
        transmission: 'Transmisión CVT',
        botName: 'Asistente Stara',
        botStatus: 'En Línea',
        inputPlaceholder: 'Pregunta algo...',
        roleJunior: 'Operador Junior',
        roleSenior: 'Operador Senior',
        videoTitle: 'Video Aula Práctica',
        watchTutorial: 'Ver Tutorial',
        lessonProgress: 'Progreso del Entrenamiento',
        nextLesson: 'Próxima lección: Desmontaje y Limpieza',
        standardProc: 'Procedimiento Estándar',
        mandatoryChange: 'Cambio obligatorio cada 500h de uso. Use llave 12mm.',
        visualStep: 'Paso a paso visual para evitar fugas en la brida.',
        juniorTag: 'JUNIOR',
        operationalTag: 'OPERACIONAL',
        viewManual: 'Ver Manual',
        continueCourse: 'Continuar Curso',

        // Achievements
        level: 'Nivel',
        totalXp: 'XP Total',
        nextLevel: 'Próximo Nivel',
        completedCourses: 'Cursos Completos',
        badgeFirstLogin: 'Primeros Pasos',
        badgeFirstLoginDesc: 'Accedió al simulador por primera vez.',
        badgePumpMaster: 'Maestro de Bombas',
        badgePumpMasterDesc: 'Completó el módulo de mantenimiento de bombas sin errores.',
        badgeSafety: 'Seguridad Primero',
        badgeSafetyDesc: 'Realizó todos los procedimientos de seguridad antes de la operación.',
        badgeMechanic: 'Mecánico Certificado',
        badgeMechanicDesc: 'Acumule 100 horas de simulación técnica.',
        locked: 'Bloqueado',
        unlocked: 'Desbloqueado',

        // Chat Scripts
        trainingGreeting: 'Hola Vivian. ¿Continuamos el entrenamiento?',
        trainingUserSim: '¡Sí, claro! ¿Dónde nos quedamos?',
        trainingBotResponse: '¡Genial! Aquí está el video sobre el Módulo de Bomba donde lo dejamos.',
        operationGreeting: 'Hola Roberto. ¿Cuál es tu duda?',
        operationUserSim: '¿Cuál es el par recomendado para los tornillos de la brida?',
        operationBotResponse: 'El par recomendado es de 120Nm. Asegúrese de usar una llave dinamométrica calibrada.',

        // Double Click Interaction
        trainingClickIntro: 'Has seleccionado: ',
        trainingClickPrompt: '¿Qué te gustaría aprender sobre esta pieza?',
        optHowItWorks: '¿Cómo funciona?',
        optCommonErrors: 'Errores Comunes',

        opClickIntro: 'Diagnóstico Rápido: ',
        opClickDetails: '🛠 Herramienta: Llave 12mm | ⚠️ Par: 45Nm | 🔄 Cambio: Si hay fugas.',

        // AI Glasses Mode
        aiGlassesMode: 'Modo Gafas IA',
        startRemoteAssist: 'Iniciar Asistencia Remota',
        listening: 'Escuchando...',
        processing: 'Procesando...',
        systemCheck: 'Verificación del Sistema',
        connectionStable: 'Conexión Estable',
        endCall: 'Finalizar Llamada',
        glassesOverlayText: 'Analizando componente visual. Módulo de Bomba detectado. Temperatura normal.',
    }
};
